import Head from "next/head";
import Navigation from './navigation'
import {
  AiFillTwitterCircle,
  AiFillLinkedin,
  AiFillYoutube,
} from "react-icons/ai";
import { BsFillMoonStarsFill } from "react-icons/bs";
import { useState } from "react";
import deved from "../public/cristian.png";
import code from "../public/code.png";
import design from "../public/design.png";
import Image from "next/image";
import web1 from "../public/portfolio/store-estore.png";
import web2 from "../public/portfolio/smart-brain.png";
import web3 from "../public/portfolio/netflix-img.png";
import web4 from "../public/portfolio/dotsgame.png";
import web5 from "../public/portfolio/social-app.png";
import web6 from "../public/portfolio/fitness-img.png";

export default function Home() {
  const [darkMode, setDarkMode] = useState(false);

  
  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className=" bg-white px-10 dark:bg-gray-900 md:px-20 lg:px-40">
        <header className="py-6 flex justify-between items-center mx-auto px-8 md:px-14 lg:px-24 dark:text-white">
            <h1>Dark Mode <span>&#8594;</span></h1>
            <ul className="flex items-center tx-color-white">
              <li className="flex items-center">
                <BsFillMoonStarsFill
                  onClick={() => setDarkMode(!darkMode)}
                  className="cursor-pointer text-2xl"
                />
              </li>
            </ul>
            
            <Navigation />
        </header>

        {/* section 1  */}
        <section className="min-h-screen">
          <div className="text-center p-10 py-10">
            <a id="home" className="">
              <h2 className="text-5xl py-2 text-teal-600 font-medium dark:text-teal-400 md:text-6xl">
                Cristian Sanchez
              </h2>    
            </a>
            <h3 className="text-2xl py-2 dark:text-white md:text-3xl">
              Web Developer
            </h3>
            <p className="text-md py-5 leading-8 text-gray-800 dark:text-gray-200 max-w-xl mx-auto md:text-xl">
              As a developer I bring forth a motivated attitude along with a variety of coding skills.
            </p>
            <div className="text-5xl flex justify-center gap-16 py-3 text-gray-600 dark:text-gray-400">
              <a href='https://twitter.com/Cristian_14715' target="_blank" rel="noreferrer" >
                <AiFillTwitterCircle />
              </a>
              <a href='https://www.linkedin.com/in/cristian-s-b03951219/' target="_blank" rel="noreferrer" >
                <AiFillLinkedin href="https://www.linkedin.com/in/cristian-s-b03951219/" />
              </a>
              <a href='https://www.youtube.com/channel/UCdXKvZmgrU3sWxtYEOKNBVg' target="_blank" rel="noreferrer">
                <AiFillYoutube href='https://www.youtube.com/channel/UCdXKvZmgrU3sWxtYEOKNBVg'/>
              </a>
            </div>
            <div className="mx-auto bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 relative overflow-hidden mt-20 md:h-96 md:w-96">
              <Image src={deved} layout="fill" objectFit="cover" alt='' />
            </div>
          </div>
        </section>

        {/* section 2  */}
        <section>
          <div>
            <h3 className="text-3xl py-1 dark:text-white ">What I Do</h3>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
              Since the beginning of my journey as a developer, I<span>&#39;</span>ve attended classes at 
              <span className="text-teal-500"> General Assemply </span>and an alumni at <span className="text-teal-500"> 
               Zero To Mastery </span>. I am Continue to learn and develop my skills as a Full Stack devloper.
            </p>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
              My experiences are: 
            </p>
          </div>
          <div className="lg:flex gap-10">
            <div className="text-center shadow-lg p-10 rounded-xl my-10  dark:bg-white flex-1">
              <Image src={design} width={100} height={100} alt='' />
              <div className=' shadow-xl p-10 rounded-xl my-10 flex-1 '>
                <h3 className="text-lg font-medium pt-8 pb-2  ">
                  Front-End Development
                </h3>
                <p className="py-2">
                  Focuses on layout, animations, content organization, navigation, graphics.
                </p>
                <div>
                  <div className='p-10'>
                    <h4 className="text-teal-600">Languages:</h4>
                    <p className="text-gray-800 py-1">JavaScript: Typescript</p>
                    <p className="text-gray-800 py-1">HTML</p>
                    <p className="text-gray-800 py-1">CSS</p>  
                  </div>
                  <div className='p-10'>
                    <h4 className="text-teal-600">Framework:</h4>
                    <p className="text-gray-800 py-1">ReactJS</p>
                    <p className="text-gray-800 py-1">Angular 2+</p>
                    <p className="text-gray-800 py-1">TailWind</p>
                    <p className="text-gray-800 py-1">WordPress</p>
                    <p className="text-gray-800 py-1">Figma</p>
                  </div>
                </div>
              </div>
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white flex-1">
              <Image src={code} width={100} height={100} alt='' />
              <div className=' shadow-xl p-10 rounded-xl my-10 flex-1 '>
                <h3 className="text-lg font-medium pt-8 pb-2 ">
                  Back-End Developer
                </h3>
                <p className="py-2">
                  Focuses on building code, debugging, database management.
                </p>
                <div>
                  <div className='p-10'>
                    <h4 className="text-teal-600">Languages:</h4>
                    <p className="text-gray-800 py-1">Node.js</p>
                    <p className="text-gray-800 py-1">JavaScript</p>
                    <p className="text-gray-800 py-1">Python</p>
                  </div>
                  <div className='p-10'>
                      <h4 className="text-teal-600">Framework:</h4>
                      <p className="text-gray-800 py-1">Django</p>
                      <p className="text-gray-800 py-1">ReactJS</p>
                      <p className="text-gray-800 py-1">Express.js</p>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </section>

        {/* section 3  */}
        <section className="py-10">
          <div>
            <a id="work" className="">
              <span className="text-3xl loading-10 font-bold  py-1 dark:text-white ">Portofolio</span>
            </a>
            <p className="mt-6 text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
              Since the beginning of my journey as a Web Developer. I<span>&#39;</span>ve improved on 
              my skills as a devloper by building websites.
            </p>
          </div>
          <div className="flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap">
            <div className="basis-1/3 flex-1 ">
              <a href='https://cs-e-commerce.netlify.app/' target="_blank" rel="noreferrer">
                <Image
                  className="rounded-lg object-cover"
                  layout="responsive"
                  src={web1}
                  alt=''
                  
                />
              </a>
            </div>
            <div className="basis-1/3 flex-1">
              <a href='https://smart-brain--frontend.herokuapp.com/' target="_blank" rel="noreferrer">
              <Image
                className="rounded-lg object-cover"
                layout="responsive"
                src={web2}
                alt=''
              />
              </a>
            </div>
            <div className="basis-1/3 flex-1">
              <a href='https://netflix-reactjs-cristian.netlify.app/' target="_blank" rel="noreferrer">
                <Image
                  className="rounded-lg object-cover"
                  layout="responsive"
                  src={web3}
                  alt=''
                />
              </a>
            </div>
            <div className="basis-1/3 flex-1">
              <a href='https://63993dab88e78b6f91c08ddc--super-figolla-c0c901.netlify.app/'  target="_blank" rel="noreferrer">
              <Image
                className="rounded-lg object-cover"
                layout="responsive"
                src={web4}
                alt=''
                
              />
              </a>
            </div>
            <div className="basis-1/3 flex-1">
              <a href='' target="_blank" rel="noreferrer">
              <Image
                className="rounded-lg object-cover"
                layout="responsive"
                src={web5}
                alt=''
              />
              </a>
            </div>
            <div className="basis-1/3 flex-1">
              <a href='https://fitnessapp-evogym.netlify.app/'>
                <Image
                  className="rounded-lg object-cover"
                  layout="responsive"
                  src={web6}
                  alt=''
                />
              </a>
            </div>
          </div>
        </section>

        {/* section 4 */}
        <div className="container pb-12 mt-10 flex justify-between items-center mx-auto px-8 md:px-14 lg:px-24 w-full dark:text-white">
          <div className="w-full text-black dark:text-white">
            <h2 id="hire" className="text-2xl loading-10 font-bold">Hire me</h2>
            <p className="mt-6 text-slate-400">Feel free to to contact me any time, through my method below.</p>
              <a href="https://mailchi.mp/e374a212b5dd/ztm-students">
                <button className="mt-10 block bg-gradient-to-r from-cyan-500 to-teal-500 text-white text-sm p-1 border-none rounded-md">Contact Me</button> 
              </a>
              <div className="mb-12 pb-12 mt-10 dark:text-white"> 
                <p className="text-secondary">541-709-6181</p>
                <a href="https://mailchi.mp/a6d14010e8ee/cristian-sanchez" className="text-secondary underline mt-3 block">cristian.manu7@gmail.com</a>
              </div>
              <a href='#home'>
                <button className="mt-10 block bg-gradient-to-r from-cyan-500 to-teal-500 text-white text-sm p-1 border-none rounded-md">Back To The Top</button>
              </a>
          </div>
		    </div>
      </main>
    </div>
  );
}